# This is a LizaRB Application
# Learn more: https://lizarb.org/

class App

  # Choose your Name

  name "project_1"

  # Choose your Gemfile

  gemfile "Gemfile"

  # Choose your Application Directory

  directory "app"

  # Choose your Log Transparency
  #
  #    1       2     3     4      5      6        7
  # :lowest :lower :low :normal :high :higher :highest
  #
  # log_boot  4
  # log_level 4

  # Choose your sources of Environment Variables

  # env_vars ".env", ":directory.env", ":directory.:mode.env", mandatory: false

  # Systems help you organize your application's dependencies and RAM memory usage.

  system :dev # default
  system :my_aaaab
  system :my_aaaac
  system :my_aaaad
  system :my_aaaae
  system :my_aaaaf
  system :my_aaaag
  system :my_aaaah
  system :my_aaaai
  system :my_aaaaj
  system :my_aaaak
  system :my_aaaal
  system :my_aaaam
  system :my_aaaan
  system :my_aaaao
  system :my_aaaap
  system :my_aaaaq
  system :my_aaaar
  system :my_aaaas
  system :my_aaaat
  system :my_aaaau
  system :my_aaaav
  system :my_aaaaw
  system :my_aaaax
  system :my_aaaay
  system :my_aaaaz
  system :my_aaaba
  system :my_aaabb
  system :my_aaabc
  system :my_aaabd
  system :my_aaabe
  system :my_aaabf
  system :my_aaabg
  system :my_aaabh
  system :my_aaabi
  system :my_aaabj
  system :my_aaabk
  system :my_aaabl
  system :my_aaabm
  system :my_aaabn
  system :my_aaabo
  system :my_aaabp
  system :my_aaabq
  system :my_aaabr
  system :my_aaabs
  system :my_aaabt
  system :my_aaabu
  system :my_aaabv
  system :my_aaabw
  system :my_aaabx
  system :my_aaaby
  system :my_aaabz
  system :my_aaaca
  system :my_aaacb
  system :my_aaacc
  system :my_aaacd
  system :my_aaace
  system :my_aaacf
  system :my_aaacg
  system :my_aaach
  system :my_aaaci
  system :my_aaacj
  system :my_aaack
  system :my_aaacl
  system :my_aaacm
  system :my_aaacn
  system :my_aaaco
  system :my_aaacp
  system :my_aaacq
  system :my_aaacr
  system :my_aaacs
  system :my_aaact
  system :my_aaacu
  system :my_aaacv
  system :my_aaacw
  system :my_aaacx
  system :my_aaacy
  system :my_aaacz
  system :my_aaada
  system :my_aaadb
  system :my_aaadc
  system :my_aaadd
  system :my_aaade
  system :my_aaadf
  system :my_aaadg
  system :my_aaadh
  system :my_aaadi
  system :my_aaadj
  system :my_aaadk
  system :my_aaadl
  system :my_aaadm
  system :my_aaadn
  system :my_aaado
  system :my_aaadp
  system :my_aaadq
  system :my_aaadr
  system :my_aaads
  system :my_aaadt
  system :my_aaadu
  system :my_aaadv
  system :my_aaadw
  system :my_aaadx
  system :my_aaady
  system :my_aaadz
  system :my_aaaea
  system :my_aaaeb
  system :my_aaaec
  system :my_aaaed
  system :my_aaaee
  system :my_aaaef
  system :my_aaaeg
  system :my_aaaeh
  system :my_aaaei
  system :my_aaaej
  system :my_aaaek
  system :my_aaael
  system :my_aaaem
  system :my_aaaen
  system :my_aaaeo
  system :my_aaaep
  system :my_aaaeq
  system :my_aaaer
  system :my_aaaes
  system :my_aaaet
  system :my_aaaeu
  system :my_aaaev
  system :my_aaaew
  system :my_aaaex
  system :my_aaaey
  system :my_aaaez
  system :my_aaafa
  system :my_aaafb
  system :my_aaafc
  system :my_aaafd
  system :my_aaafe
  system :my_aaaff
  system :my_aaafg
  system :my_aaafh
  system :my_aaafi
  system :my_aaafj
  system :my_aaafk
  system :my_aaafl
  system :my_aaafm
  system :my_aaafn
  system :my_aaafo
  system :my_aaafp
  system :my_aaafq
  system :my_aaafr
  system :my_aaafs
  system :my_aaaft
  system :my_aaafu
  system :my_aaafv
  system :my_aaafw
  system :my_aaafx
  system :my_aaafy
  system :my_aaafz
  system :my_aaaga
  system :my_aaagb
  system :my_aaagc
  system :my_aaagd
  system :my_aaage
  system :my_aaagf
  system :my_aaagg
  system :my_aaagh
  system :my_aaagi
  system :my_aaagj
  system :my_aaagk
  system :my_aaagl
  system :my_aaagm
  system :my_aaagn
  system :my_aaago
  system :my_aaagp
  system :my_aaagq
  system :my_aaagr
  system :my_aaags
  system :my_aaagt
  system :my_aaagu
  system :my_aaagv
  system :my_aaagw
  system :my_aaagx
  system :my_aaagy
  system :my_aaagz
  system :my_aaaha
  system :my_aaahb
  system :my_aaahc
  system :my_aaahd
  system :my_aaahe
  system :my_aaahf
  system :my_aaahg
  system :my_aaahh
  system :my_aaahi
  system :my_aaahj
  system :my_aaahk
  system :my_aaahl
  system :my_aaahm
  system :my_aaahn
  system :my_aaaho
  system :my_aaahp
  system :my_aaahq
  system :my_aaahr
  system :my_aaahs
  system :my_aaaht
  system :my_aaahu
  system :my_aaahv
  system :my_aaahw
  system :my_aaahx
  system :my_aaahy
  system :my_aaahz
  system :my_aaaia
  system :my_aaaib
  system :my_aaaic
  system :my_aaaid
  system :my_aaaie
  system :my_aaaif
  system :my_aaaig
  system :my_aaaih
  system :my_aaaii
  system :my_aaaij
  system :my_aaaik
  system :my_aaail
  system :my_aaaim
  system :my_aaain
  system :my_aaaio
  system :my_aaaip
  system :my_aaaiq
  system :my_aaair
  system :my_aaais
  system :my_aaait
  system :my_aaaiu
  system :my_aaaiv
  system :my_aaaiw
  system :my_aaaix
  system :my_aaaiy
  system :my_aaaiz
  system :my_aaaja
  system :my_aaajb
  system :my_aaajc
  system :my_aaajd
  system :my_aaaje
  system :my_aaajf
  system :my_aaajg
  system :my_aaajh
  system :my_aaaji
  system :my_aaajj
  system :my_aaajk
  system :my_aaajl
  system :my_aaajm
  system :my_aaajn
  system :my_aaajo
  system :my_aaajp
  system :my_aaajq
  system :my_aaajr
  system :my_aaajs
  system :my_aaajt
  system :my_aaaju
  system :my_aaajv
  system :my_aaajw
  system :my_aaajx
  system :my_aaajy
  system :my_aaajz
  system :my_aaaka
  system :my_aaakb
  system :my_aaakc
  system :my_aaakd
  system :my_aaake
  system :my_aaakf
  system :my_aaakg
  system :my_aaakh
  system :my_aaaki
  system :my_aaakj
  system :my_aaakk
  system :my_aaakl
  system :my_aaakm
  system :my_aaakn
  system :my_aaako
  system :my_aaakp
  system :my_aaakq
  system :my_aaakr
  system :my_aaaks
  system :my_aaakt
  system :my_aaaku
  system :my_aaakv
  system :my_aaakw
  system :my_aaakx
  system :my_aaaky
  system :my_aaakz
  system :my_aaala
  system :my_aaalb
  system :my_aaalc
  system :my_aaald
  system :my_aaale
  system :my_aaalf
  system :my_aaalg
  system :my_aaalh
  system :my_aaali
  system :my_aaalj
  system :my_aaalk
  system :my_aaall
  system :my_aaalm
  system :my_aaaln
  system :my_aaalo
  system :my_aaalp
  system :my_aaalq
  system :my_aaalr
  system :my_aaals
  system :my_aaalt
  system :my_aaalu
  system :my_aaalv
  system :my_aaalw
  system :my_aaalx
  system :my_aaaly
  system :my_aaalz
  system :my_aaama
  system :my_aaamb
  system :my_aaamc
  system :my_aaamd
  system :my_aaame
  system :my_aaamf
  system :my_aaamg
  system :my_aaamh
  system :my_aaami
  system :my_aaamj
  system :my_aaamk
  system :my_aaaml
  system :my_aaamm
  system :my_aaamn
  system :my_aaamo
  system :my_aaamp
  system :my_aaamq
  system :my_aaamr
  system :my_aaams
  system :my_aaamt
  system :my_aaamu
  system :my_aaamv
  system :my_aaamw
  system :my_aaamx
  system :my_aaamy
  system :my_aaamz
  system :my_aaana
  system :my_aaanb
  system :my_aaanc
  system :my_aaand
  system :my_aaane
  system :my_aaanf
  system :my_aaang
  system :my_aaanh
  system :my_aaani
  system :my_aaanj
  system :my_aaank
  system :my_aaanl
  system :my_aaanm
  system :my_aaann
  system :my_aaano
  system :my_aaanp
  system :my_aaanq
  system :my_aaanr
  system :my_aaans
  system :my_aaant
  system :my_aaanu
  system :my_aaanv
  system :my_aaanw
  system :my_aaanx
  system :my_aaany
  system :my_aaanz
  system :my_aaaoa
  system :my_aaaob
  system :my_aaaoc
  system :my_aaaod
  system :my_aaaoe
  system :my_aaaof
  system :my_aaaog
  system :my_aaaoh
  system :my_aaaoi
  system :my_aaaoj
  system :my_aaaok
  system :my_aaaol
  system :my_aaaom
  system :my_aaaon
  system :my_aaaoo
  system :my_aaaop
  system :my_aaaoq
  system :my_aaaor
  system :my_aaaos
  system :my_aaaot
  system :my_aaaou
  system :my_aaaov
  system :my_aaaow
  system :my_aaaox
  system :my_aaaoy
  system :my_aaaoz
  system :my_aaapa
  system :my_aaapb
  system :my_aaapc
  system :my_aaapd
  system :my_aaape
  system :my_aaapf
  system :my_aaapg
  system :my_aaaph
  system :my_aaapi
  system :my_aaapj
  system :my_aaapk
  system :my_aaapl
  system :my_aaapm
  system :my_aaapn
  system :my_aaapo
  system :my_aaapp
  system :my_aaapq
  system :my_aaapr
  system :my_aaaps
  system :my_aaapt
  system :my_aaapu
  system :my_aaapv
  system :my_aaapw
  system :my_aaapx
  system :my_aaapy
  system :my_aaapz
  system :my_aaaqa
  system :my_aaaqb
  system :my_aaaqc
  system :my_aaaqd
  system :my_aaaqe
  system :my_aaaqf
  system :my_aaaqg
  system :my_aaaqh
  system :my_aaaqi
  system :my_aaaqj
  system :my_aaaqk
  system :my_aaaql
  system :my_aaaqm
  system :my_aaaqn
  system :my_aaaqo
  system :my_aaaqp
  system :my_aaaqq
  system :my_aaaqr
  system :my_aaaqs
  system :my_aaaqt
  system :my_aaaqu
  system :my_aaaqv
  system :my_aaaqw
  system :my_aaaqx
  system :my_aaaqy
  system :my_aaaqz
  system :my_aaara
  system :my_aaarb
  system :my_aaarc
  system :my_aaard
  system :my_aaare
  system :my_aaarf
  system :my_aaarg
  system :my_aaarh
  system :my_aaari
  system :my_aaarj
  system :my_aaark
  system :my_aaarl
  system :my_aaarm
  system :my_aaarn
  system :my_aaaro
  system :my_aaarp
  system :my_aaarq
  system :my_aaarr
  system :my_aaars
  system :my_aaart
  system :my_aaaru
  system :my_aaarv
  system :my_aaarw
  system :my_aaarx
  system :my_aaary
  system :my_aaarz
  system :my_aaasa
  system :my_aaasb
  system :my_aaasc
  system :my_aaasd
  system :my_aaase
  system :my_aaasf
  system :my_aaasg
  system :my_aaash
  system :my_aaasi
  system :my_aaasj
  system :my_aaask
  system :my_aaasl
  system :my_aaasm
  system :my_aaasn
  system :my_aaaso
  system :my_aaasp
  system :my_aaasq
  system :my_aaasr
  system :my_aaass
  system :my_aaast
  system :my_aaasu
  system :my_aaasv
  system :my_aaasw
  system :my_aaasx
  system :my_aaasy
  system :my_aaasz
  system :my_aaata
  system :my_aaatb
  system :my_aaatc
  system :my_aaatd
  system :my_aaate
  system :my_aaatf
  system :my_aaatg
  system :my_aaath
  system :my_aaati
  system :my_aaatj
  system :my_aaatk
  system :my_aaatl
  system :my_aaatm
  system :my_aaatn
  system :my_aaato
  system :my_aaatp
  system :my_aaatq
  system :my_aaatr
  system :my_aaats
  system :my_aaatt
  system :my_aaatu
  system :my_aaatv
  system :my_aaatw
  system :my_aaatx
  system :my_aaaty
  system :my_aaatz
  system :my_aaaua
  system :my_aaaub
  system :my_aaauc
  system :my_aaaud
  system :my_aaaue
  system :my_aaauf
  system :my_aaaug
  system :my_aaauh
  system :my_aaaui
  system :my_aaauj
  system :my_aaauk
  system :my_aaaul
  system :my_aaaum
  system :my_aaaun
  system :my_aaauo
  system :my_aaaup
  system :my_aaauq
  system :my_aaaur
  system :my_aaaus
  system :my_aaaut
  system :my_aaauu
  system :my_aaauv
  system :my_aaauw
  system :my_aaaux
  system :my_aaauy
  system :my_aaauz
  system :my_aaava
  system :my_aaavb
  system :my_aaavc
  system :my_aaavd
  system :my_aaave
  system :my_aaavf
  system :my_aaavg
  system :my_aaavh
  system :my_aaavi
  system :my_aaavj
  system :my_aaavk
  system :my_aaavl
  system :my_aaavm
  system :my_aaavn
  system :my_aaavo
  system :my_aaavp
  system :my_aaavq
  system :my_aaavr
  system :my_aaavs
  system :my_aaavt
  system :my_aaavu
  system :my_aaavv
  system :my_aaavw
  system :my_aaavx
  system :my_aaavy
  system :my_aaavz
  system :my_aaawa
  system :my_aaawb
  system :my_aaawc
  system :my_aaawd
  system :my_aaawe
  system :my_aaawf
  system :my_aaawg
  system :my_aaawh
  system :my_aaawi
  system :my_aaawj
  system :my_aaawk
  system :my_aaawl
  system :my_aaawm
  system :my_aaawn
  system :my_aaawo
  system :my_aaawp
  system :my_aaawq
  system :my_aaawr
  system :my_aaaws
  system :my_aaawt
  system :my_aaawu
  system :my_aaawv
  system :my_aaaww
  system :my_aaawx
  system :my_aaawy
  system :my_aaawz
  system :my_aaaxa
  system :my_aaaxb
  system :my_aaaxc
  system :my_aaaxd
  system :my_aaaxe
  system :my_aaaxf
  system :my_aaaxg
  system :my_aaaxh
  system :my_aaaxi
  system :my_aaaxj
  system :my_aaaxk
  system :my_aaaxl
  system :my_aaaxm
  system :my_aaaxn
  system :my_aaaxo
  system :my_aaaxp
  system :my_aaaxq
  system :my_aaaxr
  system :my_aaaxs
  system :my_aaaxt
  system :my_aaaxu
  system :my_aaaxv
  system :my_aaaxw
  system :my_aaaxx
  system :my_aaaxy
  system :my_aaaxz
  system :my_aaaya
  system :my_aaayb
  system :my_aaayc
  system :my_aaayd
  system :my_aaaye
  system :my_aaayf
  system :my_aaayg
  system :my_aaayh
  system :my_aaayi
  system :my_aaayj
  system :my_aaayk
  system :my_aaayl
  system :my_aaaym
  system :my_aaayn
  system :my_aaayo
  system :my_aaayp
  system :my_aaayq
  system :my_aaayr
  system :my_aaays
  system :my_aaayt
  system :my_aaayu
  system :my_aaayv
  system :my_aaayw
  system :my_aaayx
  system :my_aaayy
  system :my_aaayz
  system :my_aaaza
  system :my_aaazb
  system :my_aaazc
  system :my_aaazd
  system :my_aaaze
  system :my_aaazf
  system :my_aaazg
  system :my_aaazh
  system :my_aaazi
  system :my_aaazj
  system :my_aaazk
  system :my_aaazl
  system :my_aaazm
  system :my_aaazn
  system :my_aaazo
  system :my_aaazp
  system :my_aaazq
  system :my_aaazr
  system :my_aaazs
  system :my_aaazt
  system :my_aaazu
  system :my_aaazv
  system :my_aaazw
  system :my_aaazx
  system :my_aaazy
  system :my_aaazz
  system :my_aabaa
  system :my_aabab
  system :my_aabac
  system :my_aabad
  system :my_aabae
  system :my_aabaf
  system :my_aabag
  system :my_aabah
  system :my_aabai
  system :my_aabaj
  system :my_aabak
  system :my_aabal
  system :my_aabam
  system :my_aaban
  system :my_aabao
  system :my_aabap
  system :my_aabaq
  system :my_aabar
  system :my_aabas
  system :my_aabat
  system :my_aabau
  system :my_aabav
  system :my_aabaw
  system :my_aabax
  system :my_aabay
  system :my_aabaz
  system :my_aabba
  system :my_aabbb
  system :my_aabbc
  system :my_aabbd
  system :my_aabbe
  system :my_aabbf
  system :my_aabbg
  system :my_aabbh
  system :my_aabbi
  system :my_aabbj
  system :my_aabbk
  system :my_aabbl
  system :my_aabbm
  system :my_aabbn
  system :my_aabbo
  system :my_aabbp
  system :my_aabbq
  system :my_aabbr
  system :my_aabbs
  system :my_aabbt
  system :my_aabbu
  system :my_aabbv
  system :my_aabbw
  system :my_aabbx
  system :my_aabby
  system :my_aabbz
  system :my_aabca
  system :my_aabcb
  system :my_aabcc
  system :my_aabcd
  system :my_aabce
  system :my_aabcf
  system :my_aabcg
  system :my_aabch
  system :my_aabci
  system :my_aabcj
  system :my_aabck
  system :my_aabcl
  system :my_aabcm
  system :my_aabcn
  system :my_aabco
  system :my_aabcp
  system :my_aabcq
  system :my_aabcr
  system :my_aabcs
  system :my_aabct
  system :my_aabcu
  system :my_aabcv
  system :my_aabcw
  system :my_aabcx
  system :my_aabcy
  system :my_aabcz
  system :my_aabda
  system :my_aabdb
  system :my_aabdc
  system :my_aabdd
  system :my_aabde
  system :my_aabdf
  system :my_aabdg
  system :my_aabdh
  system :my_aabdi
  system :my_aabdj
  system :my_aabdk
  system :my_aabdl
  system :my_aabdm
  system :my_aabdn
  system :my_aabdo
  system :my_aabdp
  system :my_aabdq
  system :my_aabdr
  system :my_aabds
  system :my_aabdt
  system :my_aabdu
  system :my_aabdv
  system :my_aabdw
  system :my_aabdx
  system :my_aabdy
  system :my_aabdz
  system :my_aabea
  system :my_aabeb
  system :my_aabec
  system :my_aabed
  system :my_aabee
  system :my_aabef
  system :my_aabeg
  system :my_aabeh
  system :my_aabei
  system :my_aabej
  system :my_aabek
  system :my_aabel
  system :my_aabem
  system :my_aaben
  system :my_aabeo
  system :my_aabep
  system :my_aabeq
  system :my_aaber
  system :my_aabes
  system :my_aabet
  system :my_aabeu
  system :my_aabev
  system :my_aabew
  system :my_aabex
  system :my_aabey
  system :my_aabez
  system :my_aabfa
  system :my_aabfb
  system :my_aabfc
  system :my_aabfd
  system :my_aabfe
  system :my_aabff
  system :my_aabfg
  system :my_aabfh
  system :my_aabfi
  system :my_aabfj
  system :my_aabfk
  system :my_aabfl
  system :my_aabfm
  system :my_aabfn
  system :my_aabfo
  system :my_aabfp
  system :my_aabfq
  system :my_aabfr
  system :my_aabfs
  system :my_aabft
  system :my_aabfu
  system :my_aabfv
  system :my_aabfw
  system :my_aabfx
  system :my_aabfy
  system :my_aabfz
  system :my_aabga
  system :my_aabgb
  system :my_aabgc
  system :my_aabgd
  system :my_aabge
  system :my_aabgf
  system :my_aabgg
  system :my_aabgh
  system :my_aabgi
  system :my_aabgj
  system :my_aabgk
  system :my_aabgl
  system :my_aabgm
  system :my_aabgn
  system :my_aabgo
  system :my_aabgp
  system :my_aabgq
  system :my_aabgr
  system :my_aabgs
  system :my_aabgt
  system :my_aabgu
  system :my_aabgv
  system :my_aabgw
  system :my_aabgx
  system :my_aabgy
  system :my_aabgz
  system :my_aabha
  system :my_aabhb
  system :my_aabhc
  system :my_aabhd
  system :my_aabhe
  system :my_aabhf
  system :my_aabhg
  system :my_aabhh
  system :my_aabhi
  system :my_aabhj
  system :my_aabhk
  system :my_aabhl
  system :my_aabhm
  system :my_aabhn
  system :my_aabho
  system :my_aabhp
  system :my_aabhq
  system :my_aabhr
  system :my_aabhs
  system :my_aabht
  system :my_aabhu
  system :my_aabhv
  system :my_aabhw
  system :my_aabhx
  system :my_aabhy
  system :my_aabhz
  system :my_aabia
  system :my_aabib
  system :my_aabic
  system :my_aabid
  system :my_aabie
  system :my_aabif
  system :my_aabig
  system :my_aabih
  system :my_aabii
  system :my_aabij
  system :my_aabik
  system :my_aabil
  system :my_aabim
  system :my_aabin
  system :my_aabio
  system :my_aabip
  system :my_aabiq
  system :my_aabir
  system :my_aabis
  system :my_aabit
  system :my_aabiu
  system :my_aabiv
  system :my_aabiw
  system :my_aabix
  system :my_aabiy
  system :my_aabiz
  system :my_aabja
  system :my_aabjb
  system :my_aabjc
  system :my_aabjd
  system :my_aabje
  system :my_aabjf
  system :my_aabjg
  system :my_aabjh
  system :my_aabji
  system :my_aabjj
  system :my_aabjk
  system :my_aabjl
  system :my_aabjm
  system :my_aabjn
  system :my_aabjo
  system :my_aabjp
  system :my_aabjq
  system :my_aabjr
  system :my_aabjs
  system :my_aabjt
  system :my_aabju
  system :my_aabjv
  system :my_aabjw
  system :my_aabjx
  system :my_aabjy
  system :my_aabjz
  system :my_aabka
  system :my_aabkb
  system :my_aabkc
  system :my_aabkd
  system :my_aabke
  system :my_aabkf
  system :my_aabkg
  system :my_aabkh
  system :my_aabki
  system :my_aabkj
  system :my_aabkk
  system :my_aabkl
  system :my_aabkm
  system :my_aabkn
  system :my_aabko
  system :my_aabkp
  system :my_aabkq
  system :my_aabkr
  system :my_aabks
  system :my_aabkt
  system :my_aabku
  system :my_aabkv
  system :my_aabkw
  system :my_aabkx
  system :my_aabky
  system :my_aabkz
  system :my_aabla
  system :my_aablb
  system :my_aablc
  system :my_aabld
  system :my_aable
  system :my_aablf
  system :my_aablg
  system :my_aablh
  system :my_aabli
  system :my_aablj
  system :my_aablk
  system :my_aabll
  system :my_aablm
  system :my_aabln
  system :my_aablo
  system :my_aablp
  system :my_aablq
  system :my_aablr
  system :my_aabls
  system :my_aablt
  system :my_aablu
  system :my_aablv
  system :my_aablw
  system :my_aablx
  system :my_aably
  system :my_aablz
  system :my_aabma
  system :my_aabmb
  system :my_aabmc
  system :my_aabmd
  system :my_aabme
  system :my_aabmf
  system :my_aabmg
  system :my_aabmh
  system :my_aabmi
  system :my_aabmj
  system :my_aabmk
  system :my_aabml
  system :my_aabmm

end